app1/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from app1 import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("main.urls", namespace="main")),
    path("", include("goods.urls", namespace="catalog")),
    path("", include("goods.urls", namespace="service")),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

goods/urls.py
from django.urls import path

from goods import views

app_name = 'goods'

urlpatterns = [
    path('catalog/<slug:category_slug>/', views.catalog, name='catalog'),
    path('service/', views.staff, name='index'),      #Персонал
]

main/urls.py
from django.urls import path

from main import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
]

goods/models.py
from django.db import models


class Categories(models.Model):
    name = models.CharField(max_length=150, unique=True, verbose_name='Название')
    slug = models.SlugField(max_length=200, unique=True, blank=True, null=True, verbose_name='URL')
    description = models.TextField(max_length=1500, blank=True, verbose_name='Описание')

    class Meta:
        db_table = 'category'
        verbose_name: str = 'Категорию'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name


class Service(models.Model):
    name = models.CharField(max_length=150, unique=True, verbose_name='Название')
    price = models.PositiveIntegerField(default=0, verbose_name='Цена, руб.')
    category = models.ForeignKey(to=Categories, on_delete=models.CASCADE, verbose_name='Категория', blank=True, null=True)

    class Meta:
        db_table = 'Service'
        verbose_name = 'услугу'
        verbose_name_plural = 'Услуги'

    def __str__(self):
        return self.name


class Staff(models.Model):
    name = models.CharField(max_length=150, unique=True, verbose_name='Имя')
    job = models.CharField(max_length=150, blank=True, verbose_name='Специальность')
    description = models.TextField(verbose_name='Описание')
    image = models.ImageField(upload_to='staff_images', verbose_name='Изображение')
    category = models.ForeignKey(to=Categories, on_delete=models.CASCADE, verbose_name='Категория', null=True)
    
    class Meta:
        db_table = 'Staff'
        verbose_name = 'Персонал'
        verbose_name_plural = 'Персонал'

    def __str__(self):
        return self.name

goods/views.py
from django.shortcuts import render, get_object_or_404
from goods.models import Service, Staff, Categories



def staff(request, category_slug=None):
    category = None
    if category_slug:
        category = get_object_or_404(Categories, slug=category_slug)
        staff = Staff.objects.filter(category=category)
    else:
        staff = Staff.objects.all()

    context = {
        "title": "Наши сотрудники",
        "staff": staff,
        "category": category  # передаем категорию в контекст
    }
    return render(request, "goods/service.html", context)




def catalog(request, category_slug=None):
    if category_slug == "all":
        category_name = "Все категории"
        category_description = "Описание всех категорий"
        services = Service.objects.all()
        staff = Staff.objects.all()
    else:
        category = get_object_or_404(Categories, slug=category_slug)
        category_name = category.name
        category_description = category.description  # Получаем описание категории
        services = Service.objects.filter(category=category)
        staff = Staff.objects.filter(category=category)
    
    context = {
        "title": f"Услуги по категории {category_name}",
        "category_name": category_name,
        "category_description": category_description,  # Передаем описание категории в контекст
        "services": services,
        "staff": staff
    }
    return render(request, "goods/catalog.html", context)

main/views.py
from django.http import HttpResponse
from django.shortcuts import render

# def index(request):
#     context = {
#         'title': 'Медицинский Центр неврологии и ортопедии'}
#     return render(request, 'main/index.html', context)

def index(request):
    context = {
        'title': 'Медицинский Центр неврологии и ортопедии',

    }
    return render(request, 'main/index.html', context)


def about(request):
    context = {
        'title': 'О нас',
        'content': "О нас",
        'text_on_page': """Наш медицинский центр открылся в 2015 году.  Основатель центра врач травматолог-ортопед Малик Андрей Юрьевич.
На сегодняшний день «Медицинский центр неврологии и ортопедии» возглавляет врач-невролог Малик Ксения Валерьевна.   
У нас работают высококвалифицированные специалисты, центр оснащен современной аппаратурой для оказания  диагностической и консультативной помощи, а также проведения реабилитации пациентов.   
Прием ведут врачи высшей категории , регулярно повышающие уровень своей квалификации.  
 В составе центра работает специализированный оздоровительно-тренажерный зал."""
    }

    return render(request, 'main/about.html', context)

goods/templates/goods/catalog.html
{% extends "main/base.html" %}
{% load static %}
{% load goods_tags %}



{% block content %}

<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <div class="card mb-3 bg-white">
                <div class="card-body">
                    <h1 class="title">{{ category_name }}</h1>
                    <p class="card-text text-start">{{ category_description }}</p> 
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <!-- Категории -->
        <div class="col-lg-3" id="scrollingMenu">
            <div class="card mb-3 bg-white">
                <div class="card-body">
                    <h3 class="price-table table priceTable p">Консультации врачей</h3>
                    {% tag_categories as categories %}
                    {% for category in categories %}
                    {% if category.slug != "procedurnyj-kabinet" and category.slug != "adaptivnaya-fizkultura" %}
                        <!-- Ссылки на категории -->
                        <a href="{% url 'goods:catalog' category.slug %}" class="list-group-item price-table table priceTable p">{{ category.name }}</a>
                    {% endif %}
                    {% endfor %}
                </div>
            </div>
        </div>
        <!-- Блок с staff_detail -->
        <div class="card mb-3 bg-white">
            {% include "goods/staff_detail.html" %}
        </div>
        
            <!-- Блок с услугами -->
            <div class="row">
    <!-- Блок с услугами -->
    <div class="col-lg-6">
        <div class="card mb-3">
            <div class="card-body bg-white">
                <div class="mb-5">
                    <h3>Услуги</h3>
                    <div class="d-flex justify-content-between align-items-center mb-3">
                        <!-- Пустой контейнер для кнопки, оставляем скрытым -->
                        <div id="emptyButtonContainer" style="display: none;"></div>
                    </div>                        
                    <div class="collapse show" id="servicesCollapse">
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="d-flex flex-column">
                                    <table class="price-table table priceTable p">
                                        <thead>
                                            <tr>
                                                <th scope="col" class="text-start">Название услуги</th>
                                                <th scope="col" class="text-start">Цена</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            {% if request.path != "/catalog/adaptivnaya-fizkultura/" and request.path != "/catalog/procedurnyj-kabinet/" and request.path != "/catalog/diagnostika/" %}
                                                {% tag_service as service %}
                                                <tr>
                                                    <td class="text-start">{{ service.0.name }}</td>
                                                    <td class="text-start">{{ service.0.price }} руб</td>
                                                </tr>
                                                <tr>
                                                    <td class="text-start">{{ service.1.name }}</td>
                                                    <td class="text-start">{{ service.1.price }} руб</td>
                                                </tr>
                                            {% endif %}
                                            {% for service in services %}
                                                {% if forloop.counter <= 1 %}
                                                    <tr>
                                                        <td class="text-start">{{ service.name }}</td>
                                                        <td class="text-start">{{ service.price }} руб</td>
                                                    </tr>
                                                {% endif %}
                                            {% endfor %}
                                        </tbody>
                                    </table>
                                    {% if services|length > 1 %}
                                        <div class="extra-services collapse" id="extraServices">
                                            <table class="price-table table priceTable p">
                                                <tbody>
                                                    {% for service in services %}
                                                        {% if forloop.counter > 1 %}
                                                            <tr>
                                                                <td class="text-start">{{ service.name }}</td>
                                                                <td class="text-start">{{ service.price }} руб</td>
                                                            </tr>
                                                        {% endif %}
                                                    {% endfor %}
                                                </tbody>
                                            </table>
                                        </div>
                                        <button class="btn btn-link toggle-services" type="button" data-bs-toggle="collapse" data-bs-target="#extraServices" aria-expanded="false" aria-controls="extraServices">
                                            <img src="{% static "images/updown.png" %}" alt="Показать все услуги">
                                        </button>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div> 

    <!-- Блок с каруселью специалистов -->
    <div class="col-lg-6"> 
        <div class="card mb-3">
            <div class="card-body bg-white">
                <h3>Специалисты</h3>
                <div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
                    <div class="carousel-indicators">
                        {% for staff_member in staff %}
                            <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="{{ forloop.counter0 }}" {% if forloop.first %}class="active"{% endif %}></button>
                        {% endfor %}
                    </div>
                    <div class="carousel-inner">
                        {% for staff_member in staff %}
                            <div class="carousel-item {% if forloop.first %}active{% endif %}">
                                <img src="{{ staff_member.image.url }}" class="d-block w-100" alt="...">
                                <div class="carousel-caption d-none d-md-block">
                                    <h5>{{ staff_member.name }}</h5>
                                    <p>{{ staff_member.description }}</p>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
                        <span class="carousel-control-prev-icon1" aria-hidden="true"></span>
                        <span class="visually-hidden">Previous</span>
                    </button>
                    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
                        <span class="carousel-control-next-icon1" aria-hidden="true"></span>
                        <span class="visually-hidden">Next</span>
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>

            
  
        
               
    </div>
</div>

{% endblock content %}

goods/templates/goods/service.html
{% extends "main/base.html" %}
{% load static %}



{% block content %}

<div class="container">
    <h1>Наши специалисты</h1>
    <div class="row">
        <div class="col-lg-4 offset-lg-4">
            <div class="card border-primary rounded custom-shadow">
                <div class="card-body custom">
                    <img src="{{ staff.2.image.url }}" alt="..." class="img-fluid" width="300" height="200">
                    <p class="card-title">{{ staff.2.name }}</p>
                    <p class="card-text">{{ staff.2.description }}</p>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        {% for s in staff %}
            {% if s.id != 4 %}
                <div class="col-lg-4 col-md-6 p-4">
                    <div class="card border-primary rounded custom-shadow">
                        <div class="card-body custom">
                            <img src="{{ s.image.url }}" alt="..." class="img-fluid" width="300" height="200">
                            <p class="card-title">{{ s.name }}</p>
                            <p class="card-text">{{ s.description }}</p>
                        </div>
                    </div>
                </div>
            {% endif %}
        {% endfor %}
    </div>
</div>

{% endblock content %}

main/templates/main/about.html
{% extends "main/base.html" %}

{% load static %}

{% block content %}
    <div class="mt-5 pt-5 bg-white custom-shadow rounded">
        <h2 class="m-2"><strong>{{ content }}</strong></h2>
        <p class="m-2">{{ text_on_page }}</p>
    </div>
{% endblock content %}

 

main/templates/main/base.html
{% load static %}
{% load goods_tags %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static "images/mal.png" %}">
    <link rel="stylesheet" href="{% static '/css/index.css' %}"> <!-- Ссылка на ваш CSS файл -->
    <title>{{ title }}</title>
</head>
<body>
<header>
    <div class="col-lg-8 col-md-12 mt-5 pt-5">
        <nav class="navbar navbar-dark bg-dark navbar-custom fixed-top" style="z-index: 1000;">
            <div class="container-fluid">
                <!-- Логотип -->
                <div class="d-flex justify-content-end align-items-center flex-grow-1">
                    <a class="navbar-brand mr-auto" href="/">
                        <img src="{% static 'images/mal.png' %}" alt="Logo">
                    </a>
                    <a href="/" class="navbar-text mr-3" style="text-decoration: none;">Медицинский центр неврологии и ортопедии</a>
                </div>                               
                <!-- Ссылки -->
                <div class="d-flex justify-content-center align-items-center flex-grow-1">
                    <a class="nav-link mx-3" href="/">Главная</a>
                    <!-- Медицинские услуги с выпадающим списком -->
                    <div class="dropdown">
                        <a class="nav-link mx-3 dropdown-toggle" href="#" role="button" id="dropdownMenuLinkServices" data-bs-toggle="dropdown" aria-expanded="false">
                        Консультации специалистов
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="dropdownMenuLinkServices">
                            <li><a class="dropdown-item" href="{% url 'goods:catalog' 'psihologiya' %}">Психолог</a></li>
                            <li><a class="dropdown-item" href="{% url 'goods:catalog' 'kardiologiya' %}">Кардиолог</a></li>
                            <li><a class="dropdown-item" href="{% url 'goods:catalog' 'gastroenterologiya' %}">Гастроэнтеролог</a></li>
                            <li><a class="dropdown-item" href="{% url 'goods:catalog' 'nevrologiya' %}">Невролог</a></li>
                            <li><a class="dropdown-item" href="{% url 'goods:catalog' 'diagnostika' %}">Узи</a></li>
                            <li><a class="dropdown-item" href="{% url 'goods:catalog' 'hirurgiya' %}">Хирургия</a></li>
                            <li><a class="dropdown-item" href="{% url 'goods:catalog' 'osteopatiya' %}">Остеопатия</a></li>
                        </ul>
                    </div>
                    <!-- Профили лечения -->
                    <div class="dropdown">
                        <a class="nav-link mx-3 dropdown-toggle" href="#" role="button" id="dropdownMenuLinkTreatment" data-bs-toggle="dropdown" aria-expanded="false">
                        Наши услуги
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="dropdownMenuLinkTreatment">
                            <li><a class="dropdown-item" href="{% url "goods:catalog" "procedurnyj-kabinet" %}">Процедурный кабинет</a></li>
                            <li><a class="dropdown-item" href="{% url "goods:catalog" "adaptivnaya-fizkultura" %}">Адаптивная физкультура</a></li>
                        </ul>
                    </div>
                    <!-- Еще -->
                    <div class="dropdown">
                        <a class="nav-link mx-3 dropdown-toggle" href="#" role="button" id="dropdownMenuLinkMore" data-bs-toggle="dropdown" aria-expanded="false">
                            Еще
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="dropdownMenuLinkMore">
                            <li><a class="dropdown-item" href="{% url "main:about" %}">О нас</a></li>
                            <li><a class="dropdown-item" href="#">Контакты</a></li>
                            <li><a class="dropdown-item" href="#">Вакансии</a></li>
                        </ul>
                    </div>
                    <a class="nav-link mx-3" href="{% url "goods:index" %}">Наши специалисты</a>
                </div>
            </div>
        </nav>
    </div>
</header>
    <section>
        {% block content %}
        {% endblock content %}
    </section>
{% comment %} <footer class="py-4 bg-dark footer-custom">
    <div class="container-fluid"> <!-- Используем container-fluid для растяжения на всю ширину -->
        <p class="m-0 text-center text-white">Copyright &copy; Медицинский центр неврологии и ортопедии</p>
    </div>
</footer> {% endcomment %}
    

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>

main/templates/main/index.html
{% extends "main/base.html" %}
{% load static %}
{% load goods_tags %}

{% block content %}
<div class="container-fluid carousel-container">
  <div class="row justify-content-center">
    <!-- Левые контейнеры -->
    {% comment %} <div class="col-lg-2 col-md-12 mt-md-4">
      <div class="card mb-3" style="width: 18rem;">
        <div class="card-body bg-white">
            <h5 class="card-title">Невролог</h5>
            <p class="card-text">Лечение заболевания нервной системы, позвоночника и сосудов головного мозга.</p>
            <a class="btn btn-primary" href="{% url 'goods:catalog' 'nevrologiya' %}">
                <img src="{% static "images/nurse.png" %}" alt="Запись">
            </a>    
        </div>
    </div>    
      <div class="card mb-3" style="width: 18rem;">
        <div class="card-body bg-white">
            <h5 class="card-title">Кардиолог</h5>
            <p class="card-text">Специалист по сердцу: диагностика, лечение, профилактика болезней.</p>
            <a class="btn btn-primary" href="{% url 'goods:catalog' 'kardiologiya' %}">
                <img src="{% static "images/cardiology.png" %}" alt="Запись">
            </a> 
        </div>
    </div>   
    </div> {% endcomment %}
  
    
    <!-- Карусель -->
    <div class="col-lg-6 col-md-12">
      <div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-inner">
          <div class="carousel-item active">
            <img src="{% static "images/slide11.jpg" %}" class="d-block w-100" alt="...">
            <div class="carousel-caption d-none d-md-block text-red bg-yellow">
              <h5>У нас работают лучшие специалисты.</h5>
              <p>Пациентов нашей клиники встречают и консультируют приветливые администраторы, лечат – внимательные и компетентные врачи.</p>
            </div>
          </div>
          <div class="carousel-item">
            <img src="{% static "images/slide22.png" %}" class="d-block w-100" alt="...">
            <div class="carousel-caption d-none d-md-block text-red bg-yellow">
              <h5>Медтехника</h5>
              <p>На территории нашего медицинского центра работает магазин ортопедических товаров. В наличии имеются различные бандажи, ортезы, корсеты. Также, можно оформить заказ.</p>
            </div>
          </div>
          <div class="carousel-item">
            <img src="{% static "images/gymm.jpg" %}" class="d-block w-100" alt="...">
            <div class="carousel-caption d-none d-md-block text-red bg-yellow">
              <h5>Тренажерный зал</h5>
              <p> Наш оздоровительно-тренажерный зал идеально подходит для новичков. Мы работаем под присмотром специалистов и по индивидуальной программе для каждого пациента. Проводятся как индивидуальные так и групповые занятия.</p>
            </div>
          </div>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Next</span>
        </button>
      </div>
    </div>

    <!-- Правые контейнеры -->
    {% comment %} <div class="col-lg-2 col-md-12 mt-md-4">
      <div class="card mb-3" style="width: 18rem;">
        <div class="card-body bg-white">
            <h5 class="card-title">Психолог</h5>
            <p class="card-text">Поддержка в сложных ситуациях, забота о вашем эмоциональном состоянии.</p>
            <a class="btn btn-primary" href="{% url 'goods:catalog' 'psihologiya' %}">
                <img src="{% static "images/doctor.png" %}" alt="Запись">
            </a>
        </div>
    </div>
    <div class="card mb-3" style="width: 18rem;">
        <div class="card-body bg-white">
            <h5 class="card-title">Гастроэнтеролог</h5>
            <p class="card-text">Диагностика и лечение желудочно-кишечных проблем, забота о вашем здоровье.</p>
            <a class="btn btn-primary" href="{% url 'goods:catalog' 'gastroenterologiya' %}">
                <img src="{% static "images/stomach.png" %}" alt="Запись">
            </a>
        </div>  
    </div> {% endcomment %}
    
  </div>
</div>


<hr class="border border-primary only-one">

<div class="container">
  <figure class="text-center">
    <blockquote class="blockquote">
      <p>В удобное для вас время, вы можете посетить врачей разных специальностей, получить квалифицированные медицинские услуги и посетить оздоровительно-тренажерный зал.</p>
    </blockquote>
    <figcaption class="blockquote-footer">
      команда <cite title="Source Title">Медицинского центра</cite>
    </figcaption>
  </figure>
</div>

<hr class="border border-primary only-one">

<div class="container">
  <h1 class="title">Мы предлагаем нашим клиентам</h1>
</div>

{% comment %} <div class="categories-container">
  <div class="category">
      <div class="category-image">
          <img src="{% static "images/doctor.png" %}" alt="Психология">
      </div>
      <h5><a href="{% url 'goods:catalog' 'psihologiya' %}">Психология</a></h5>
  </div>

  <div class="category">
    <div class="category-image">
        <img src="{% static "images/stomach.png" %}" alt="Гастроэнтеролог">
    </div>
    <h5><a href="{% url 'goods:catalog' 'gastroenterologiya' %}">Гастроэнтеролог</a></h5>
  </div>

  <div class="category">
    <div class="category-image">
        <img src="{% static "images/nurse.png" %}" alt="Невролог">
    </div>
    <h5><a href="{% url 'goods:catalog' 'nevrologiya' %}">Невролог</a></h5>
  </div>

  <div class="category">
    <div class="category-image">
        <img src="{% static "images/cardiology.png" %}" alt="Кардиолог">
    </div>
    <h5><a href="{% url 'goods:catalog' 'kardiologiya' %}">Кардиолог</a></h5>
  </div>

  <div class="category">
    <div class="category-image">
        <img src="{% static "images/hirurg.png" %}" alt="Хирург">
    </div>
    <h5><a href="{% url 'goods:catalog' 'hirurgiya' %}">Хирург</a></h5>
  </div>

  <div class="category">
    <div class="category-image">
        <img src="{% static "images/osteopat.png" %}" alt="Остеопат">
    </div>
    <h5><a href="{% url 'goods:catalog' 'osteopatiya' %}">Остеопат</a></h5>
  </div>

  <div class="category">
    <div class="category-image">
        <img src="{% static "images/x-ray.png" %}" alt="Аппаратное исследование">
    </div>
    <h5><a href="{% url 'goods:catalog' 'diagnostika' %}">Аппаратное исследование</a></h5>
  </div>
</div> {% endcomment %}
<div class="xd">
  <div class="categories-column">
    <div class="category">
      <p class="con"> Консультации специалистов</p>
      <hr class="border border-primary only-one">
      <div class="category-image">
        <img src="{% static "images/doctor.png" %}" alt="Психология">
      </div>
      <h5><a href="{% url 'goods:catalog' 'psihologiya' %}">Психология</a></h5>
    </div>

    <div class="category">
      <div class="category-image">
        <img src="{% static "images/stomach.png" %}" alt="Гастроэнтеролог">
      </div>
      <h5><a href="{% url 'goods:catalog' 'gastroenterologiya' %}">Гастроэнтеролог</a></h5>
    </div>

    <div class="category">
      <div class="category-image">
        <img src="{% static "images/nurse.png" %}" alt="Невролог">
      </div>
      <h5><a href="{% url 'goods:catalog' 'nevrologiya' %}">Невролог</a></h5>
    </div>

    <div class="category">
      <div class="category-image">
        <img src="{% static "images/cardiology.png" %}" alt="Кардиолог">
      </div>
      <h5><a href="{% url 'goods:catalog' 'kardiologiya' %}">Кардиолог</a></h5>
    </div>

    <div class="category">
      <div class="category-image">
        <img src="{% static "images/hirurg.png" %}" alt="Хирург">
      </div>
      <h5><a href="{% url 'goods:catalog' 'hirurgiya' %}">Хирург</a></h5>
    </div>

    <div class="category">
      <div class="category-image">
        <img src="{% static "images/osteopat.png" %}" alt="Остеопат">
      </div>
      <h5><a href="{% url 'goods:catalog' 'osteopatiya' %}">Остеопат</a></h5>
    </div>

    <div class="category">
      <div class="category-image">
        <img src="{% static "images/x-ray.png" %}" alt="Аппаратное исследование">
      </div>
      <h5><a href="{% url 'goods:catalog' 'diagnostika' %}">Аппаратное исследование</a></h5>
    </div>
  </div>

  <div class="large-image-container">
    <div class="large-image">
      <img src="{% static "images/clinica.jpg" %}" alt="Big Image">
    </div>
    <div class="large-image-overlay"></div>
  </div>
</div>






{% endblock content %}